<a href="/" class="logo fleft">
			<img src="/skin/images/tennismania.png" alt="Tennismania">
</a>
		
<script type="application/x-moraso" src="Navigation:main"></script>
<!-- <nav class="fright">
			<ul>
				<li><a href="index.html" class="navactive">Home</a></li>
				<li><a href="about.html">Über uns</a></li>
			</ul>
			<ul>
				<li><a href="works.html">Kurse</a></li>
				<li><a href="services.html">Vereine</a></li> 
			</ul>
			<ul>
				<li><a href="blog.html">News</a></li>
				<li><a href="contact.html">Kontakt</a></li>
			</ul>
</nav> -->