<div class="row">    
    <article class="large-9 columns">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h1
        </script>

        <script type="application/x-moraso" src="Template:Article">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/main/article/default.phtml 
        </script>
    </article>

    <aside class="large-3 columns">      
        <script type="application/x-moraso" src="Template:Aside">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/main/aside/default.phtml 
        </script>
    </aside>

    <script type="application/x-moraso" src="Navigation:meta">
        template = meta
    </script>
</div>

