<div class="row">    
    <article class="large-9 columns">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h1
        </script>

        <script type="application/x-moraso" src="HTML.Content:Content"></script>

        <div class="row">
            <div class="large-6 columns">
                <script type="application/x-moraso" src="Article.Include:1"></script>
            </div>
            
            <div class="large-6 columns">
                <script type="application/x-moraso" src="Article.Include:2"></script>
            </div>
        </div>
        
    </article>

    <aside class="large-3 columns">        
        <script type="application/x-moraso" src="Navigation.Sub:Sub"></script>

        <p>Ich bin die Sidebar</p>
    </aside>

    <script type="application/x-moraso" src="Navigation:meta">
        template = meta
    </script>
</div>

