
    
    
    
 <div class="divide-top">
	<footer class="grid-wrap">
		<ul class="grid col-one-third social">
			<li><a href="http://www.facebook.com" target="_blank">Facebook</a></li>
			<li><a href="http://www.twitter.com" target="_blank">Twitter</a></li>
			<li>&copy; 2013 - <a href="http://www.tennismania.biz" target="_blank">tennismania</a></li>
		</ul>
	
		<div class="up grid col-one-third ">
			<a href="#navtop" title="Go back up">&uarr;</a>
		</div>
		
		<nav class="grid col-one-third ">
		<!-- <ul>
			<li><a href="index.html">Home</a></li>
			<li><a href="about.html">Über uns</a></li>
			<li><a href="works.html">Kurse</a></li>
			<li><a href="services.html">Vereine</a></li>
			<li><a href="blog.html">News</a></li>
			<li><a href="contact.html">Kontakt</a></li>
		</ul> -->
		
		<script type="application/x-moraso" src="Navigation:meta">
        template = meta
		</script>

	</nav>
	</footer>
</div>   