Ext.getCmp('viewport-east').setVisible(false);
Ext.getCmp('viewport-west').setVisible(false);

var center = Ext.getCmp('viewport-center');
center.removeAll();

center.add({
	id: 'dashboard',
	unstyled: true,
	layout: 'column',
	bodyStyle:'padding:4px'
});

<?php $plugins = array(); for ($i = 0; $i < count($this->plugins); $i++) {$plugins[] = "'" . $this->url(array('plugin' => $this->plugins[$i]['name']->name, 'namespace' => $this->plugins[$i]['namespace']), 'dplugin') . "'"; } ?>

Ext.aitsu.load([<?php echo implode(',', $plugins); ?>], function() {
	Ext.getCmp('viewport').doLayout();
});
