<div class="row">
    <div class="large-12 columns">
        <script type="application/x-moraso" src="Navigation:main"></script>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <script type="application/x-moraso" src="Image:featured">
            width = 1000
            height = 400
            template = featured
        </script>
    </div>
</div>


<script type="application/x-moraso" src="Image:Test">
    float = config
    height = config
    render = config
    style = config
    template = config
    width = config
    
    attr = config
</script>
