<p class="fleft">
<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
	tag = h1
</script>
</p>
		
<script type="application/x-moraso" src="HTML.Content:Content"></script>

<h2 id="Tenniscamps">Tenniscamps</h2>
<script type="application/x-moraso" src="List.Articles:Tenniscamps">
	categories = 12
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>

<h2 id="Wochenendcamps">Wochenendcamps</h2>
<script type="application/x-moraso" src="List.Articles:Wochenendcamps">
	categories = 13
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>

<h2 id="Turnierspielcamps">Turnierspielcamps</h2>
<script type="application/x-moraso" src="List.Articles:Turnierspielcamps">
	categories = 14
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>


<h2 id="Sparringcamps">Sparringcamps</h2>
<script type="application/x-moraso" src="List.Articles:Sparringcamps">
	categories = 15
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>
