<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | TENNISMANIA"
        </script>

        <!-- BaseHref :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
        <!-- BaseHref :: End -->

        <!-- CanonicalTag :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
        <!-- CanonicalTag :: End -->

        <!-- Meta Tags :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
        <!-- Meta Tags :: End -->

        <!-- Meta Geo Tags :: Start -->
        <meta name="geo.region" content="DE-NI" />
        <meta name="geo.placename" content="Schaan" />
        <meta name="geo.position" content="52.80912;9.14234" />
        <meta name="ICBM" content="52.80912, 9.14234" />
        <!-- Meta Geo Tags :: End -->

        <!-- Windows 8 Tile :: Start -->
        <meta name="application-name" content="moraso CMS" /> 
        <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <!-- Windows 8 Tile :: End -->

        <!-- CSS :: Start -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="/skin/css/style.css">
		<link href='http://fonts.googleapis.com/css?family=Viga' rel='stylesheet' type='text/css'>
        <!-- CSS :: End -->

        <!-- JS :: Start -->
        <script src="/skin/js/vendor/prefixfree.min.js"></script>
        <script src="/skin/js/vendor/custom.modernizr.js"></script>
        <!-- JS :: End -->

        <!-- Google Fonts :: Start -->
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
        <!-- Google Fonts :: End -->

        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body style="background: #f4ef4a">
	<div class="container">
        
        <!-- Header :: Start -->
        <header id="navtop">
        	<script type="application/x-moraso" src="Template:Header">
            	defaultTemplate = default

                template.default.name = Standard
                template.default.file = templates/header/default.phtml 
            </script>
        </header>
        <!-- Header :: End -->

        <!-- Content :: Start -->
        <div class="home-page main">
                <script type="application/x-moraso" src="Template:Main">
                    defaultTemplate = default

                    template.default.name = Standard
                    template.default.file = templates/main/default.phtml 

                    template.start.name = Start
                    template.start.file = templates/main/start.phtml 
                </script>
        </div>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <footer id="footer">
            <div class="row">
                <div class="large-12 columns">
                    <script type="application/x-moraso" src="Template:Footer">
                        defaultTemplate = default

                        template.default.name = Standard
                        template.default.file = templates/footer/default.phtml 
                    </script>
                </div>
            </div>
        </footer>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        <script src="http://code.jquery.com/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="/skin/js/jquery-1.7.2.min.js"><\/script>')</script>
		<!--[if (gte IE 6)&(lte IE 8)]>

		<script src="js/selectivizr.js"></script>
		<![endif]-->

		<script src="/skin/js/jquery.flexslider-min.js"></script>
		<script src="/skin/js/scripts.js"></script>
		<!-- <script src="/skin/js/jquery.backstretch.min.js"></script>
			<script>
			$.backstretch(["/skin/images/tennisplatz.jpg"]);
			</script>
		-->

		<!-- Asynchronous Google Analytics snippet. Change UA-XXXXX-X to be your site's ID. -->
        <!-- JS :: End -->
    </body>
</html>
