<ul >
<?php foreach ($this->article as $article) : ?>
  <li style="margin: 0 0 0 15px;" <?php if($this->idart == $article->idart) : ?><?php endif; ?>><a<?php if($this->idart == $article->idart) : ?> class="active" <?php else : ?> class=""<?php endif; ?> title="<?php echo $article->articletitle; ?>" href="{ref:idart-<?php echo $article->idart; ?>}" ><?php echo $article->articletitle; ?></a></li>
<?php endforeach; ?>
</ul>