<div class="about-page main grid-wrap">
	<header class="grid col-full">
		<hr>
		<p class="fleft"><script type="application/x-moraso" src="Navigation.BreadCrumb:Breadcrumb"> </script></p>
	</header>

		<aside class="grid col-one-quarter mq2-col-full">
		<script type="application/x-moraso" src="Template:Aside">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/main/aside/default.phtml 
        </script>
		</aside>

		<section class="grid col-three-quarters mq2-col-full">
		<script type="application/x-moraso" src="Template:Article">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/main/article/default.phtml
            
            template.kurse.name = Kurse
            template.kurse.file = templates/main/article/kurse.phtml 
        </script>
		</section>
</div>		