<section class="grid-wrap" >
	<header class="grid col-full">
		<hr>
		<p class="fleft"><script type="application/x-moraso" src="Navigation.BreadCrumb:Breadcrumb"> </script></p>
	</header>
		
	<div class="grid col-one-half mq2-col-full">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h1
        </script>

        <script type="application/x-moraso" src="HTML.Content:Content"></script>

        <script type="application/x-moraso" src="Article.Include:1"></script>
        <script type="application/x-moraso" src="Article.Include:2"></script>
    </div>
        
    
     <div class="slider grid col-one-half mq2-col-full">
     
     <script type="application/x-moraso" src="Image:featured">
				width = 1000
				height = config
				default.height = 400
				render = config
				template = config
				default.config = slider
	 </script>
	</div>
</section>

<section class="services grid-wrap">
		<header class="grid col-full">
			<hr>
			<h2 class="fleft">Termine</h2>
			<!-- <a href="/de/kurse" class="arrow fright">weitere...</a> -->
		</header>

		<article class="grid col mq3-col-full">

<h3 id="Tenniscamps">Tenniscamps</h3>
<script type="application/x-moraso" src="List.Articles:Tenniscamps">
	categories = 12
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>

<h3 id="Wochenendcamps">Wochenendcamps</h3>
<script type="application/x-moraso" src="List.Articles:Wochenendcamps">
	categories = 13
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>

<h3 id="Turnierspielcamps">Turnierspielcamps</h3>
<script type="application/x-moraso" src="List.Articles:Turnierspielcamps">
	categories = 14
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>


<h3 id="Sparringcamps">Sparringcamps</h3>
<script type="application/x-moraso" src="List.Articles:Sparringcamps">
	categories = 15
	useOfStartArticle = 2
	orderBy = artsort
	template = kurse
	limit = 99
	populateWith.intro.index = Einleitung
	populateWith.content.index = Fliesstext
</script>
<br><br><br>

		
		
		
		
		
		</article>

		
		<!--<article class="grid col-one-third mq3-col-full">
			<aside>27.07.2013</aside>
			<h5>Götzis</h5>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim.</p>
		</article>
		
		<article class="grid col-one-third mq3-col-full">
			<aside>05.08.2013</aside>
			<h5>Feldkirch</h5>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim.</p>
		</article>
		
		<article class="grid col-one-third mq3-col-full">
			<aside>16.08.2013</aside>
			<h5>Rankweil</h5>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim.</p>
		</article>-->
	</section>

<section class="works grid-wrap">
	<header class="grid col-full">
			<hr>
			<h2 class="fleft">News</h2>
			<!-- <a href="works.html" class="arrow fright">weitere...</a> -->
		</header>
	
			<!-- <figure class="grid col-one-quarter mq2-col-one-half">
				<a href="work1.html">
				<img src="img/img.jpg" alt="">
				<span class="zoom"></span>
				</a>
				<figcaption>
					<a href="work1.html" class="arrow">Project page!</a>
					<p>Lorem ipsum dolor set amet</p>
				</figcaption>
			</figure> -->
			
	</section>